### PR TITLE
Feat support multipe token cache

### PR DESCRIPTION
**Pull request by ruster-cn**
1. support multipe token cache: redis and mem
2.fix help message miss option

### CODE REVIEW

**Comment by liqiang-fit2cloud** [comment]
Thank you very much for the PR.:thumbsup:

But what if requirepass is enabled and db need to be specified for the redis?

**Comment by ruster-cn** [comment]
> But what if requirepass is enabled and db need to be specified for the redis?

its possibile that make  redis connection configuration complete.

**Comment by liqiang-fit2cloud** [comment]
That would be very kind of you to finish the rest. :blush:

**Comment by ruster-cn** [comment]
> That would be very kind of you to finish the rest. 😊

I revised and submitted pr，so i close this

**Pull request closed without merging**
